services:
  - docker

os: linux

dist: focal

language: python

python:
  - '3.7'

env:
  - BROKER_URI=amqp://infrabbit3:infrabbit3@$localhost:5673/

branches:
  only:
    - master

install:
  - pip install pip --upgrade
  - python setup.py develop
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
  - dev/start_infrabbitmq3_dependencies.sh

script:
  - sleep 20
  - all_tests

after_script:
  - dev/stop_infrabbitmq3_dependencies.sh
  - docker logout

notifications:
  email:
    - bifer@alea-soluciones.com
